# Generated by Django 4.0.3 on 2022-08-27 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=64, unique=True, verbose_name='имя')),
                ('link', models.CharField(default='-', max_length=64)),
                ('users_id', models.CharField(default='-', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='-', max_length=256)),
                ('data_create', models.DateTimeField(default=datetime.datetime(2022, 8, 29, 6, 27, 21, 167803, tzinfo=utc))),
                ('data_update', models.DateTimeField(default=datetime.datetime(2022, 8, 29, 6, 27, 21, 167803, tzinfo=utc))),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='активна')),
                ('user', models.OneToOneField(default='-', on_delete=django.db.models.deletion.CASCADE, to='todoapp.project')),
            ],
        ),
    ]
