# Generated by Django 4.0.3 on 2022-09-01 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todo_data_create_alter_todo_data_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 12, 27, 10, 113076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='data_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 12, 27, 10, 113076, tzinfo=utc)),
        ),
    ]
