# Generated by Django 4.0.3 on 2022-08-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.TextField(blank=True, max_length=100, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(db_index=True, default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
